### ISSUE TITLE
iOS Text Size & Bold Text Issues

### ISSUE THREAD

**Issue by jtkeyva** [coingaming/moon_flutter#394]
I have my settings to show a larger text and bold text on my iPhone. The moon components do not adhere to these size or bold changes. In your example app the text in the menu list on the bottom left "composites, combobox, single select etc" are all big and bold. But when I go to a page that shows these components they are not big and not bold.

Any plans to integrate these accessibility features?

**Comment by Kypsis** [comment]
There are multiple factors in play here. Our components have size variants with corresponding height, gap, padding and text/icon size props. Also since MDS uses w500 for titles but a lot of non DMSans don't even have a variant for w500. Thus Flutter picks one font weight lower variant, w400 ie regular font weight. Then there is a very deliberate choice of not having vertical paddings in container-like components for text to be able to grow vs having the component grow. 

Overall the whole topic of accessibility is on todo list.

**Comment by Kypsis** [comment]
With v1.0.0 we have frozen all feature work and are focusing on v2 which should address the topic of accessibility properly.
