### ISSUE TITLE
Feature request: Loading button

### ISSUE THREAD

**Issue by ysfsl** [coingaming/moon_flutter#409]
I think it would be good to have a loading button. We can implement it with the current button, but it’s not very useful because if the button is full-width, the loading indicator shows on the left or right side, but not close to the label. We have to configure something for it to work very well.

MoonButton(isLoading: true)

We could use it like this.

**Comment by Kypsis** [comment]
But this is quite literally the thing we have tried to avoid as much as possible with MDS, falling into the trap of "propitis". The just one more prop approach tends to add up pretty fast to significant maintenance cost. 

Since the components are following the concept of using "slots" and you can pass in widgets to that slot, if I understand your use-case correctly you could get the effect you are looking by passing in Align widget that has a loader of your choice as child.
