### ISSUE TITLE
Json token to design

### ISSUE THREAD

**Issue by alirezat66** [coingaming/moon_flutter#449]
Do we have any solution, for converting tokens (json file of figma) to Design?

**Comment by Kypsis** [comment]
Not sure if I understand your question correctly. If you mean converting Figma tokens json output to moon_design token format there is this repo to take inspiration from: [moon_tokens](https://github.com/coingaming/moon-tokens/tree/main). Since we have opted to not use StyleDictionary that repo is outdated though. For v2 we plan to update that solution to use Figma variables instead.
