### ISSUE TITLE
How Can the Scale Effect Be Disabled on a Button?

### ISSUE THREAD

**Issue by huykgit98** [coingaming/moon_flutter#453]

**Comment by Kypsis** [comment]
The base MoonButton includes a showScaleEffect prop for toggling the scale effect. MoonFilledButton and related variants don’t expose this prop since they are opinionated implementations aligned with our Moon Design System. Still, these variants are thin wrappers around MoonButton, making it easy to create a custom version if needed.

**Comment by huykgit98** [comment]
> The base MoonButton includes a showScaleEffect prop for toggling the scale effect. MoonFilledButton and related variants don’t expose this prop since they are opinionated implementations aligned with our Moon Design System. Still, these variants are thin wrappers around MoonButton, making it easy to create a custom version if needed.

ty sir
